language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

branches:
    only:
        - /^v\d\.\d/
cache:
  directories:
    - vendor

before_script:
  - phpenv global 5.3
  - composer install --dev --no-interaction
  - phpenv global "$TRAVIS_PHP_VERSION"

script:
  - ant -f misc/ant/build.xml tests

after_script:
  - php vendor/bin/coveralls
