#!/bin/bash

function run_phpcs {
    phpcs --report-emacs "${1}"
}

function run_phpmd {
    phpmd "${1}" text codesize,design,naming,unusedcode
}

case "${1}" in
    --about )
        echo "Perform static analysis of php source files"
        ;;
    * )
        error=0

        # stash away unstaged changes to run tests on code to be commited
        git stash -u --keep-index || exit 1

        # call out to tools
        for file in `git diff --cached --name-only --diff-filter=ACM`; do
            if echo $file | grep -e '\.php$' > /dev/null ; then
                run_phpcs "${file}"
                if [ $? -ne 0 ] ; then
                    error=1
                fi

                run_phpmd "${file}"
                if [ $? -ne 0 ] ; then
                    error=1
                fi
            fi
        done

        # restore working directory
        git stash pop -q --index
        exit $error
        ;;
esac
